quote/urls.py
from django.urls import path
from rest_framework import routers

from . import views

app_name = 'quote'

router = routers.DefaultRouter()
router.register(r'quoteItem', views.QuoteItemViewSet)
router.register(r'orderItem', views.OrderItemViewSet)
router.register(r'orderInfo', views.OrderInfoViewSet)

urlpatterns = [
    path('', views.genre_select, name='genre'),
    path('order/<str:genre>', views.quote_order, name='order'),
    path('item_list/', views.QuoteItemList.as_view(), name='item_list'),
    path('delete_item/<int:pk>', views.delete_quote_item, name='delete_item'),
    path('register_destination/', views.register_destination, name='register_destination'),
    path('add_destination/', views.AddDestination.as_view(), name='add_destination'),
    path('add_requester/', views.add_requester, name='add_requester'),
    path('create_pdf/<int:pk>', views.AllCreatePdf.as_view(), name='create_pdf'),
    path('orderinfo/', views.OrderInfoView.as_view(), name='orderinfo'),
    path('mypage/', views.OrderInfoMyView.as_view(), name='mypage'),
    path('orderinfo_detail/<int:pk>', views.OrderInfoDetailView.as_view(), name='orderinfo_detail')
]

stock/urls.py
from django.urls import path
from rest_framework import routers

from . import views

app_name = 'stock'

router = routers.DefaultRouter()
router.register(r'option', views.OptionViewSet)
router.register(r'storage', views.StorageItemViewSet)
router.register(r'kittingPlan', views.KittingPlanViewSet)
router.register(r'orderItem', views.OrderItemViewSet)
router.register(r'storageCart', views.StorageCartViewSet)
router.register(r'approve', views.ApproveViewSet)
router.register(r'orderInfo', views.OrderInfoViewSet)

urlpatterns = [
	path('', views.top_page, name='top'),
	path('construction', views.construction, name='construction'),
	path('item_list', views.StorageItemListView.as_view(), name='storage_list'),
	path('item_list_admin', views.StorageItemAdminListView.as_view(), name='storage_list_admin'),
	path('detail/<int:pk>', views.StorageItemDetailView.as_view(), name='storage_detail'),
	path('detail_admin/<int:pk>', views.StorageItemDetailAdminView.as_view(), name='storage_detail_admin'),
	path('get_data/', views.create_storage_data, name='get_data'),
	path('create/', views.StorageItemCreateView.as_view(), name='storage_create'),
	path('update/<int:pk>', views.StorageItemUpdateView.as_view(), name='storage_update'),
	path('optionCreate/', views.OptionCreateView.as_view(), name='option_create'),
	path('cart/', views.StorageCartView.as_view(), name='cart'),
	path('add_item/<int:pk>', views.add_item, name='add_item'),
	path('reduce_item/<int:pk>', views.reduce_cart, name='reduce_cart'),
	path('remove_item/<int:pk>', views.remove_cart, name='remove_cart'),
	path('approve/', views.ApproveView.as_view(), name='approve'),
	path('approve_create/', views.ApproveCreateView.as_view(), name='approve_create'),
	path('approve_update/<int:pk>', views.ApproveUpdateView.as_view(), name='approve_update'),
	path('add_orderInfo/', views.add_order_info, name='add_order_info'),
	path('confirm/<int:pk>', views.ConfirmView.as_view(), name='confirm'),
	path('my_order_info/', views.MyOrderInfoView.as_view(), name='my_order_info'),
	path('order_info_list/', views.OrderInfoListView.as_view(), name='orderinfo_list'),
	path('order_info_update/<int:pk>', views.OrderInfoUpdateView.as_view(), name='orderinfo_update'),
	path('order_info_detail/<int:pk>', views.OrderInfoDetailView.as_view(), name='orderinfo_detail'),
	path('order_info_detail_admin/<int:pk>', views.OrderInfoDetailAdminView.as_view(), name='orderinfo_detail_admin'),
	path('order_info_delete_select/<int:pk>', views.OrderInfoSelectView.as_view(), name='delete_select'),
	path('order_info_status/<int:pk>', views.order_info_status_view, name='orderinfo_status'),
	path('chang_quantity/<int:pk>', views.ChangeQuantity.as_view(), name='change_quantity'),
]

user/urls.py
from django.urls import path
from rest_framework import routers

from . import views

app_name = 'user'

router = routers.DefaultRouter()
router.register(r'base', views.BaseViewSet)
router.register(r'room', views.RoomViewSet)
router.register(r'requester', views.RequesterViewSet)

urlpatterns = [
	path('requester/<int:pk>', views.RequesterUpdateView.as_view(), name='requester_update')
]

stock/models.py
from django.db import models
from django.utils import timezone

import datetime

from device.models import PCDetail
from user.models import User, Base, Requester


class BaseManager(models.Manager):
    def get_or_none(self, **kwargs):
        try:
            return self.get_queryset().get(**kwargs)
        except self.model.DoesNotExist:
            return None


class Option(models.Model):
    maker = models.CharField(
        verbose_name='メーカー',
        max_length=100
    )
    
    name = models.CharField(
        verbose_name='製品名',
        max_length=200
    )
    
    price = models.PositiveIntegerField(
        verbose_name='金額(円)'
    )
    
    quantity = models.PositiveSmallIntegerField(
        verbose_name='在庫数'
    )
    
    remarks = models.TextField(
        verbose_name='備考',
        null=True,
        blank=True
    )
    
    def __str__(self):
        return f'{self.maker}{self.name}'
    
    class Meta:
        verbose_name = '付属品'
        verbose_name_plural = '付属品'


class StorageItem(models.Model):
    objects = BaseManager()
    
    order_number = models.CharField(
        verbose_name='発注番号',
        max_length=100
    )
    
    item = models.ForeignKey(
        PCDetail,
        on_delete=models.CASCADE,
        verbose_name='在庫PC'
    )
    
    price = models.PositiveIntegerField(
        verbose_name='本体価格'
    )
    
    quantity = models.PositiveSmallIntegerField(
        verbose_name='在庫数',
        null=True,
        blank=True
    )
    
    option = models.ManyToManyField(
        Option,
        verbose_name='付属品',
        blank=True
    )
    
    total_price = models.PositiveIntegerField(
        verbose_name='合計金額',
        null=True,
        blank=True
    )
    
    base = models.ForeignKey(
        Base,
        on_delete=models.CASCADE,
        verbose_name='在庫拠点',
    )
    
    registration_at = models.DateField(
        verbose_name='登録日',
        null=True,
        blank=True
    )
    
    remarks = models.TextField(
        verbose_name='備考',
        null=True,
        blank=True
    )
    
    def save(self, *args, **kwargs):
        if self.registration_at is None and not self.id:
            self.registration_at = timezone.now()
        self.total_price = self.price
        super(StorageItem, self).save(*args, **kwargs)
        if self.id is not None:
            for option in self.option.all():
                self.total_price += option.price
        super(StorageItem, self).save(*args, **kwargs)
    
    def __str__(self):
        return f'{self.item} ({self.base})'
    
    class Meta:
        verbose_name = '貯蔵品'
        verbose_name_plural = '貯蔵品'


class KittingPlan(models.Model):
    objects = BaseManager()
    
    kitting_choice = (
        ('標準', '標準'),
        ('お急ぎ便', 'お急ぎ便')
    )
    name = models.CharField(
        verbose_name='プラン名',
        max_length=10,
        choices=kitting_choice,
        default='標準'
    )
    
    price = models.PositiveSmallIntegerField(
        verbose_name='金額',
    )
    
    due = models.PositiveSmallIntegerField(
        verbose_name='納期',
        default=7
    )
    
    def __str__(self):
        return f'{self.name} {self.price}円'
    
    class Meta:
        verbose_name = 'キッティング価格'
        verbose_name_plural = 'キッティング価格'


class OrderItem(models.Model):
    objects = BaseManager()
    
    storage_item = models.ForeignKey(
        StorageItem,
        on_delete=models.CASCADE,
        verbose_name='貯蔵品'
    )
    
    quantity = models.PositiveSmallIntegerField(
        verbose_name='数量',
        default=1
    )
    
    ordered = models.BooleanField(
        verbose_name='確保済み',
        default=False
    )
    
    kitting_plan = models.ForeignKey(
        KittingPlan,
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    
    price = models.PositiveIntegerField(
        verbose_name='合計金額',
        null=True,
        blank=True
    )
    
    due_at = models.DateField(
        verbose_name='納品予定日',
        null=True,
        blank=True
    )
    
    requester = models.ForeignKey(
        Requester,
        on_delete=models.CASCADE,
        verbose_name='依頼者',
    )
    
    def save(self, *args, **kwargs):
        item_price = self.storage_item.total_price
        price = item_price * self.quantity
        kitting_plan = self.kitting_plan
        if kitting_plan is not None:
            now = datetime.datetime.now()
            hour = now.hour
            day = kitting_plan.due
            over_day = day + 1
            if hour >= 17:
                date = datetime.date.today() + datetime.timedelta(days=over_day)
            else:
                date = datetime.date.today() + datetime.timedelta(days=day)
            self.due_at = date
            self.price = price + kitting_plan.price
        else:
            self.price = price
        super(OrderItem, self).save(*args, **kwargs)
    
    def __str__(self):
        return f'{self.storage_item} × {self.quantity}'
    
    class Meta:
        verbose_name = '確保アイテム'
        verbose_name_plural = '確保アイテム'


class StorageCart(models.Model):
    objects = BaseManager()
    
    requester = models.ForeignKey(
        Requester,
        on_delete=models.CASCADE,
        verbose_name='依頼者'
    )
    
    order_item = models.ManyToManyField(
        OrderItem,
        verbose_name='確保アイテム',
    )
    
    price = models.PositiveIntegerField(
        verbose_name='合計金額（税込み）',
        null=True,
        blank=True
    )
    
    tax_price = models.PositiveSmallIntegerField(
        verbose_name='消費税',
        null=True,
        blank=True
    )
    
    ordered = models.BooleanField(
        default=False
    )
    
    def save(self, *args, **kwargs):
        if self.pk is not None:
            self.price = 0
            subtotal = 0
            tax = 0.1
            self.tax_price = 0
            for item in self.order_item.all():
                subtotal += item.storage_item.total_price * item.quantity
                if item.kitting_plan is not None:
                    subtotal += item.kitting_plan.price
            self.tax_price += round(subtotal * tax)
            self.price += subtotal + self.tax_price
        super(StorageCart, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.requester.user.screenname
    
    class Meta:
        verbose_name = '貯蔵品カート'
        verbose_name_plural = '貯蔵品カート'


class Approve(models.Model):
    last_name = models.CharField(
        verbose_name='姓',
        max_length=32
    )
    
    first_name = models.CharField(
        verbose_name='名',
        max_length=32,
    )
    
    dept_code = models.PositiveSmallIntegerField(
        verbose_name='部門コード'
    )
    
    dept_name = models.CharField(
        verbose_name='部門名',
        max_length=255
    )
    
    requester = models.ForeignKey(
        Requester,
        on_delete=models.CASCADE,
        verbose_name='依頼者',
        null=True,
        blank=True
    )
    
    def __str__(self):
        return f'{self.last_name} {self.first_name}'
    
    class Meta:
        verbose_name = '承認者情報'
        verbose_name_plural = '承認者情報'


class OrderInfo(models.Model):
    status_choices = (
        ('1', '準備中'),
        ('2', '確保済み'),
        ('3', 'キッティング中'),
        ('4', 'キッティング完了'),
        ('5', '納品済み')
    )
    
    objects = BaseManager()
    
    status = models.CharField(
        verbose_name='ステータス',
        max_length=2,
        choices=status_choices,
        default=1
    )
    
    number = models.CharField(
        verbose_name='受注番号',
        max_length=100
    )
    
    ticket = models.PositiveIntegerField(
        verbose_name='チケット番号',
        null=True,
        blank=True
    )
    
    storage_cart = models.ForeignKey(
        StorageCart,
        on_delete=models.CASCADE,
        verbose_name='カート'
    )
    
    approve = models.ForeignKey(
        Approve,
        on_delete=models.CASCADE,
        verbose_name='承認者情報'
    )
    
    requester = models.ForeignKey(
        Requester,
        on_delete=models.CASCADE,
        verbose_name='依頼者'
    )
    
    contact_user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='担当者',
        null=True,
        blank=True,
        related_name='contact_user'
    )
    
    ordered_at = models.DateTimeField(
        verbose_name='依頼日',
        null=True,
        blank=True
    )
    
    updated_at = models.DateTimeField(
        verbose_name='更新日',
        null=True,
        blank=True
    )
    
    completed_delivery = models.BooleanField(
        verbose_name='納品済み',
        default=False
    )
    
    delivery_at = models.DateTimeField(
        verbose_name='納品日',
        null=True,
        blank=True
    )
    
    due_at = models.DateField(
        verbose_name='納品予定日',
        null=True,
        blank=True
    )
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.ordered_at = timezone.now()
        self.updated_at = timezone.now()
        if self.delivery_at is not None:
            self.completed_delivery = True
        due = []
        for item in self.storage_cart.order_item.all():
            due.append(item.due_at)
        due.sort()
        self.due_at = due[-1]
        super(OrderInfo, self).save(*args, **kwargs)
    
    def __str__(self):
        return f'{self.number}'
    
    class Meta:
        verbose_name = '依頼内容'
        verbose_name_plural = '依頼内容'

quote/forms.py
from django import forms
from bootstrap_modal_forms.forms import BSModalModelForm

from .models import Destination


class DestinationCreateBSModalForm(BSModalModelForm):
    def __init__(self, *args, **kwargs):
        super(DestinationCreateBSModalForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
    
    class Meta:
        model = Destination
        fields = ('name',)

templates/quote/confirm.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block content %}

	<div class="container my-5 confirm">
		<div class="row">
			<div class="col-8 offset-2">
				<section class="confirm__header row">
					<div class="card">
						<div class="card-body">
							<h4 class="confirm__title">
								<i class="fas fa-check-circle"></i>
								見積もり依頼を登録しました。
							</h4>
							<div class="confirm__header__info row mt-3">
								<span>受注番号：{{ orderinfo.number }}</span>
								<span>チケット番号：{{ orderinfo.ticket }}</span>
							</div>
							<div class="row mt-3">
								<div class="col-6">
									<a href="{% url 'quote:mypage' %}">
										<span>
											見積もり履歴一覧へ<i class="fas fa-angle-double-right"></i>
										</span>
									</a>
								</div>
{#								<div class="col-3 offset-3">#}
{#									<a href="{% url 'quote:create_pdf' orderinfo.pk %}" class="btn btn-danger">PDFをダウンロードする</a>#}
{#								</div>#}
							</div>
						</div>
					</div>
				</section>
				<section class="confirm__content row mt-3">
					<div class="card">
						<div class="card-body">
							<div class="header">
								<span class="title">以下の内容で作成しました</span>
								<a href="#" class="open">展開する<i class="fa-solid fa-angle-down allow"></i></a>
							</div>
							<div class="main toggle mt-3">
								{% for quoteitem in quoteitem_list %}
									<div class="row bottom-border item">
										<div class="col-4">
											<span>
												{{ quoteitem.number }}：{{ quoteitem.item.maker }} {{ quoteitem.item.name }}
											</span>
										</div>
										<div class="col-5">
											<span>{{ quoteitem.item.spec }}</span>
										</div>
										<div class="col-3">
											<span>数量：{{ quoteitem.quantity }}</span>
										</div>
									</div>
								{% endfor %}
							</div>
						</div>
					</div>
				</section>
				<section class="confirm__footer mt-3">
					<a href="{% url 'stock:top' %}">
						<i class="fa-solid fa-arrow-circle-left"></i>
						TOPに戻る
					</a>
				</section>
			</div>
		</div>
	</div>

{% endblock content %}

{% block javascript %}
	<script src="{% static 'js/quote/quote.js' %}"></script>
	<script type="text/javascript">
		new clickAllow();
	</script>
{% endblock javascript %}

templates/quote/destination.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block content %}
	<div class="container my-5">
		<div class="row page-title">
			<h2 class="title-text">見積もり依頼先登録</h2>
		</div>
		<form action="#" method="post">
			{% csrf_token %}
			<div class="row mt-5">
				<a href="{% url 'quote:genre' %}">
					<i class="fa-solid fa-arrow-circle-left"></i>
					カテゴリー選択に戻る
				</a>
				<section class="cart col-9">
					<div class="card">
						<div class="card-body">
							<div class="row bottom-border cart__header">
								<span class="cart__title">選択中アイテム</span>
{#								<div class="apply form-check form-check-inline">#}
{#									<input type="checkbox" id="apply" class="form-check-input all-apply" name="apply" value="true">#}
{#									<label for="apply">全てに適用する</label>#}
{#								</div>#}
								<a href="#" class="add-destination">依頼先を追加する</a>
							</div>
							{% for quoteitem in quoteitem_list %}
								<div class="row bottom-border mt-3 cart__item">
									<div class="col-5">
										<p class="cart__item__name">{{ quoteitem.number }}：{{ quoteitem.item.maker }} {{ quoteitem.item.name }}</p>
										<span>{{ quoteitem.item.spec }}</span>
									</div>
									<div class="col-7 apply apply__destination">
										{% for destination in destination_list %}
											<input type="checkbox" id="destination{{ destination.pk }}-{{ quoteitem.pk }}" class="destination form-check-input"
											       name="{{ destination.pk }}" value="{{ quoteitem.pk }}">
											<label for="destination{{ destination.pk }}-{{ quoteitem.pk }}">{{ destination }}</label>
										{% endfor %}
									</div>
								</div>
							{% endfor %}
							<div class="row cart__footer">
								<span class="cart__total__title">{{ count }}個のアイテム</span>
							</div>
						</div>
					</div>
				</section>
				<section class="total col-3">
					<div class="card cart__total">
						<div class="card-body">
							<div class="row">
								<span class="cart__total__title">
									{{ count }}個のアイテム
								</span>
							</div>
							<div class="row my-3">
								{% if count > 0 %}
									<button type="submit" class="btn btn-sm btn-warning">
										次に進む
									</button>
								{% else %}
									<button type="button" class="btn btn-sm btn-secondary disabled">
										次に進めません
									</button>
								{% endif %}
							</div>
						</div>
					</div>
				</section>
			</div>
		</form>
	</div>

{% endblock content %}

{% block javascript %}
	<script src="{% static 'js/quote/quote.js' %}"></script>
	<script type="text/javascript">
		const addDestination = document.querySelector('.add-destination');
		const url = '{% url "quote:add_destination" %}';
		modal_form(addDestination, url)
		{% for destination in destination_list %}
			all_apply("{{ destination.pk }}");
		{% endfor %}
	</script>
{% endblock javascript %}

templates/quote/item_list.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block content %}
	<div class="container my-5">
		<div class="row page-title">
			<h2 class="title-text">見積もり作成予定</h2>
		</div>
		<div class="row mt-5">
			<a href="{% url 'quote:genre' %}">
				<i class="fa-solid fa-arrow-circle-left"></i>カテゴリー選択に戻る
			</a>
			<div class="col-9">
				<div class="card">
					<div class="card-body cart">
						<div class="row bottom-border cart__header">
							<span class="cart__title">選択中アイテム</span>
						</div>
						{% for quoteitem in quoteitem_list %}
							<div class="row bottom-border mt-3 cart__item">
								<p class="cart__item__name">{{ quoteitem.number }}：{{ quoteitem.item.maker }} {{ quoteitem.item.name }}</p>
								<div class="col-7">
									<span>{{ quoteitem.item.spec }}</span>
								</div>
								<div class="col-3 cart__item__menu">
									<label for="quantity{{ quoteitem.pk }}">数量：</label>
									<select name="quantity" id="quantity{{ quoteitem.pk }}">
										{% for q in quantity %}
											<option value="{{ q }}" class="cart__item__quantity"
											        {% if q == quoteitem.quantity %}selected{% endif %}>{{ q }}</option>
										{% endfor %}
									</select>
									<a href="{% url 'quote:delete_item' quoteitem.pk %}">
										削除
									</a>
								</div>
							</div>
						{% endfor %}
						<div class="row cart__footer">
							<span class="cart__total__title">{{ count }}個のアイテム</span>
						</div>
					</div>
				</div>
			</div>
			<div class="col-3">
				<div class="card cart__total">
					<div class="card-body">
						<div class="row">
							<span class="cart__total__title">
								{{ count }}個のアイテム
							</span>
						</div>
						<div class="row my-3">
							{% if count > 0 %}
								<a href="{% url 'quote:register_destination' %}" class="btn btn-sm btn-warning">
									次に進む
								</a>
							{% else %}
								<button type="button" class="btn btn-sm btn-secondary disabled">
									次に進めません
								</button>
							{% endif %}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock content %}

{% block javascript %}
	<script src="{% static 'js/quote/quote.js' %}"></script>
	<script type="text/javascript">

		{% for quoteitem in quoteitem_list %}
			const quantity_el{{ quoteitem.pk }} = document.querySelector('#quantity{{ quoteitem.pk }}');
			data = {
				number: {{ quoteitem.number }},
				item: {{ quoteitem.item.pk }},
				worker: {{ quoteitem.worker.pk }}
			}
			change_quantity(quantity_el{{ quoteitem.pk }}, data, {{ quoteitem.pk }});
		{% endfor %}


	</script>
{% endblock javascript %}

templates/quote/order_info.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block content %}

	<div class="row my-5 mx-3 myOrder">
		<a href="{% url 'stock:top' %}">
			<i class="fa-solid fa-arrow-circle-left"></i>
			TOPに戻る
		</a>
		<a href="{% url 'quote:mypage' %}">
			個人表示へ
			<i class="fa-solid fa-forward"></i>
		</a>

		{% include 'quote/modules/orderinfo_list.html' %}
	</div>
{% endblock content %}

templates/quote/orderinfo_detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}

{% block content %}

	<div class="container info-detail">
		<div class="row my-3">
	        <nav>
	            <ul class="breadcrumb">
	                <li class="breadcrumb-item">
	                    <a href="{% url 'stock:top' %}">ホーム</a>
	                </li>
	                <li class="breadcrumb-item active">
		                <a href="{% url 'quote:orderinfo' %}">履歴一覧</a>
	                </li>
		            <li class="breadcrumb-item active">
			            <span>詳細</span>
		            </li>
	            </ul>
	        </nav>
	    </div>
		<div class="row my-5">
			<div class="col-12">
				<h2 class="title-text">詳細ページ</h2>
				<section class="status row mt-3">
					<ul class="status__bar">
						{% for key, value in status.items %}
							<li class="status" id="{{ key }}">{{ value }}</li>
						{% endfor %}
					</ul>
				<div class="status-now" style="display: none">{{ orderinfo.status }}</div>
				</section>
				<section class="main row mt-5">
					<div class="col-6">
						<div class="sub-title">
							<span>詳細情報</span>
						</div>
						<table class="table">
							<tr>
								<th class="menu">受注番号</th>
								<td class="number">{{ orderinfo.number }}</td>
							</tr>
							<tr>
								<th class="menu">チケット番号</th>
								<td class="ticket">{{ orderinfo.ticket }}</td>
							</tr>
							<tr>
								<th class="menu">依頼者</th>
								<td>{{ orderinfo.cart.requester }}</td>
							</tr>
							<tr>
								<th class="menu">宛名</th>
								<td>{{ orderinfo.cart.requester.addressee }}</td>
							</tr>
							<tr>
								<th class="menu">作成者</th>
								<td>{{ orderinfo.cart.worker }}</td>
							</tr>
						</table>
					</div>
					<div class="col-5 offset-1">
						<div class="sub-title">
							<span>登録情報</span>
						</div>
						<table class="table">
							<tr>
								<th class="menu">入力日</th>
								<td>{{ orderinfo.cart.input_at }}</td>
							</tr>
							<tr>
								<th class="menu">依頼日</th>
								<td>
									{% if orderinfo.registration_at is not None %}
										{{ orderinfo.registration_at }}
									{% endif %}
								</td>
							</tr>
							<tr>
								<th class="menu">更新日</th>
								<td>
									{% if orderinfo.updated_at is not None %}
										{{ orderinfo.updated_at }}
									{% endif %}
								</td>
							</tr>
							<tr>
								<th class="menu">完了日</th>
								<td class="finish-date">
									{% if orderinfo.finished %}
										{{ orderinfo.finished_at }}
									{% endif %}
								</td>
								<td class="cart" style="display: none">{{ orderinfo.cart.pk }}</td>
								<td class="pk" style="display: none">{{ orderinfo.pk }}</td>
							</tr>
						</table>
					</div>
				</section>
				<section class="item row mt-5">
					<span class="title">依頼の情報</span>
					<div class="col-2">
						<a href="{% url 'quote:create_pdf' orderinfo.pk %}" class="btn btn-danger">見積もりPDF作成</a>
					</div>
					<div class="item__header row mt-3">
						<div class="col-3">商品</div>
						<div class="col-9">
							<div class="row">
								<div class="col-3">依頼先</div>
								<div class="col-3">依頼済み</div>
								<div class="col-3">到着済み</div>
								<div class="col-3">提供済み</div>
							</div>
						</div>

					</div>
					{% for quoteitem, orderitem_list in orderitem_dict.items %}
						<div class="item__content row">
							<div class="name col-3">
								<p>{{ quoteitem.item.maker }}：{{ quoteitem.item.name }}</p>
								<p>数量：{{ quoteitem.quantity }}</p>
							</div>
							<div class="destination col-9">
								{% for orderitem in orderitem_list %}
									<div class="row">
										<div class="col-3">{{ orderitem.destination }}</div>
										<div class="col-3 check">
											<input type="checkbox" id="ordered" class="ordered checkBox form-check-input" name="ordered"
											{% if orderitem.ordered %}disabled checked{% endif %} value="{{ quoteitem.pk }}-{{ orderitem.pk }}-{{ orderitem.destination.pk }}">
											<label for="ordered" class="ordered{{ orderitem.pk }}">
												{% if orderitem.ordered %}
													{{ orderitem.ordered_at }}
												{% endif %}
											</label>
										</div>
										<div class="col-3 check">
											<input type="checkbox" id="arrived" class="arrived checkBox form-check-input" name="arrived"
											{% if orderitem.arrived %}disabled checked{% endif %} value="{{ quoteitem.pk }}-{{ orderitem.pk }}-{{ orderitem.destination.pk }}">
											<label for="arrived" class="arrived{{ orderitem.pk }}">
												{% if orderitem.arrived %}
													{{ orderitem.arrived_at }}
												{% endif %}
											</label>
										</div>
										<div class="col-3 check">
											<input type="checkbox" id="delivered" class="delivered checkBox form-check-input" name="delivered"
											{% if orderitem.delivered %}disabled checked{% endif %} value="{{ quoteitem.pk }}-{{ orderitem.pk }}-{{ orderitem.destination.pk }}">
											<label for="delivered" class="delivered{{ orderitem.pk }}">
												{% if orderitem.delivered %}
													{{ orderitem.delivery_at }}
												{% endif %}
											</label>
										</div>
									</div>
								{% endfor %}
							</div>
						</div>
					{% endfor %}
				</section>
				<a href="{% url 'quote:mypage' %}">
					<i class="fa-solid fa-arrow-circle-left"></i>
					<span>一覧に戻る</span>
				</a>
			</div>
		</div>
	</div>

{% endblock content %}

{% block javascript %}
	<script src="{% static 'js/quote/quote.js' %}"></script>
	<script type="text/javascript">
		new checkBoxObserver();
	</script>
{% endblock javascript %}