quote/urls.py
from django.urls import path
from rest_framework import routers

from . import views

app_name = 'quote'

router = routers.DefaultRouter()
router.register(r'quoteItem', views.QuoteItemViewSet)
router.register(r'orderItem', views.OrderItemViewSet)
router.register(r'orderInfo', views.OrderInfoViewSet)

urlpatterns = [
    path('', views.genre_select, name='genre'),
    path('order/<str:genre>', views.quote_order, name='order'),
    path('item_list/', views.QuoteItemList.as_view(), name='item_list'),
    path('delete_item/<int:pk>', views.delete_quote_item, name='delete_item'),
    path('register_destination/', views.register_destination, name='register_destination'),
    path('add_destination/', views.AddDestination.as_view(), name='add_destination'),
    path('add_requester/', views.add_requester, name='add_requester'),
    path('create_pdf/<int:pk>', views.AllCreatePdf.as_view(), name='create_pdf'),
    path('orderinfo/', views.OrderInfoView.as_view(), name='orderinfo'),
    path('mypage/', views.OrderInfoMyView.as_view(), name='mypage'),
    path('orderinfo_detail/<int:pk>', views.OrderInfoDetailView.as_view(), name='orderinfo_detail')
]

stock/urls.py
from django.urls import path
from rest_framework import routers

from . import views

app_name = 'stock'

router = routers.DefaultRouter()
router.register(r'option', views.OptionViewSet)
router.register(r'storage', views.StorageItemViewSet)
router.register(r'kittingPlan', views.KittingPlanViewSet)
router.register(r'orderItem', views.OrderItemViewSet)
router.register(r'storageCart', views.StorageCartViewSet)
router.register(r'approve', views.ApproveViewSet)
router.register(r'orderInfo', views.OrderInfoViewSet)

urlpatterns = [
	path('', views.top_page, name='top'),
	path('construction', views.construction, name='construction'),
	path('item_list', views.StorageItemListView.as_view(), name='storage_list'),
	path('item_list_admin', views.StorageItemAdminListView.as_view(), name='storage_list_admin'),
	path('detail/<int:pk>', views.StorageItemDetailView.as_view(), name='storage_detail'),
	path('detail_admin/<int:pk>', views.StorageItemDetailAdminView.as_view(), name='storage_detail_admin'),
	path('get_data/', views.create_storage_data, name='get_data'),
	path('create/', views.StorageItemCreateView.as_view(), name='storage_create'),
	path('update/<int:pk>', views.StorageItemUpdateView.as_view(), name='storage_update'),
	path('optionCreate/', views.OptionCreateView.as_view(), name='option_create'),
	path('cart/', views.StorageCartView.as_view(), name='cart'),
	path('add_item/<int:pk>', views.add_item, name='add_item'),
	path('reduce_item/<int:pk>', views.reduce_cart, name='reduce_cart'),
	path('remove_item/<int:pk>', views.remove_cart, name='remove_cart'),
	path('approve/', views.ApproveView.as_view(), name='approve'),
	path('approve_create/', views.ApproveCreateView.as_view(), name='approve_create'),
	path('approve_update/<int:pk>', views.ApproveUpdateView.as_view(), name='approve_update'),
	path('add_orderInfo/', views.add_order_info, name='add_order_info'),
	path('confirm/<int:pk>', views.ConfirmView.as_view(), name='confirm'),
	path('my_order_info/', views.MyOrderInfoView.as_view(), name='my_order_info'),
	path('order_info_list/', views.OrderInfoListView.as_view(), name='orderinfo_list'),
	path('order_info_update/<int:pk>', views.OrderInfoUpdateView.as_view(), name='orderinfo_update'),
	path('order_info_detail/<int:pk>', views.OrderInfoDetailView.as_view(), name='orderinfo_detail'),
	path('order_info_detail_admin/<int:pk>', views.OrderInfoDetailAdminView.as_view(), name='orderinfo_detail_admin'),
	path('order_info_delete_select/<int:pk>', views.OrderInfoSelectView.as_view(), name='delete_select'),
	path('order_info_status/<int:pk>', views.order_info_status_view, name='orderinfo_status'),
	path('chang_quantity/<int:pk>', views.ChangeQuantity.as_view(), name='change_quantity'),
]

user/urls.py
from django.urls import path
from rest_framework import routers

from . import views

app_name = 'user'

router = routers.DefaultRouter()
router.register(r'base', views.BaseViewSet)
router.register(r'room', views.RoomViewSet)
router.register(r'requester', views.RequesterViewSet)

urlpatterns = [
	path('requester/<int:pk>', views.RequesterUpdateView.as_view(), name='requester_update')
]

templates/base.html
<!DOCTYPE html>
<html lang="ja">
{% load django_bootstrap5 %}
{% load static %}
<head>
	{% block meta %}

		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
		<meta http-equiv="x-ua-compatible" content="ie=edge">

	{% endblock %}
	{% block titel_outer %}

		<title>STOQU</title>

	{% endblock %}
	{% bootstrap_css %}
	{% bootstrap_javascript %}
	<link rel="stylesheet" href="https://unpkg.com/swiper@8/swiper-bundle.min.css"/>
	<link rel="stylesheet" href="{% static 'styles/stoqu/css/stoqu.css' %}">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"
	      integrity="sha512-Fo3rlrZj/k7ujTnHg4CGR2D7kSs0v4LLanw2qksYuRlEzO+tcaEPQogQ0KaoGN26/zrn20ImR1DfuLWnOo7aBA=="
	      crossorigin="anonymous" referrerpolicy="no-referrer"/>
</head>
<body>
{% load quote_extras %}
	<div class="global-container">
		<div class="modal fade" tabindex="-1" role="dialog" id="modal" aria-hidden="true">
			<div class="modal-dialog modal-dialog-centered">
				<div class="modal-content"></div>
			</div>
		</div>
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark navigation appear up">
			<div class="container-fluid">
				<a class="navbar-brand navigation__title item" href="{% url 'stock:top' %}">STOQU</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar"
				        aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbar">
					<ul class="navbar-nav me-auto mb-2 mb-lg-0">
						<li class="nav-item navigation__item">
							<a class="nav-link requester-update" href="#">
								<span class="requester" style="display: none">{{ request.user.pk }}</span>
								<p class="navigation__text">{{ request.user }} さん</p>
								<p class="navigation__text">
									お届け先
								</p>
								<i class="fa-solid fa-location-dot"></i>
								{% if requester.room is not None  %}
									{{ requester.room }}
								{% endif %}
								<p></p>
							</a>
						</li>
					</ul>
					<div class="navigation__search">
						<form class="d-flex">
							<input class="form-control" type="search" placeholder="まだ使えません" aria-label="Search">
							<button class="btn btn-warning" type="submit">
								<i class="fa-solid fa-magnifying-glass"></i>
							</button>
						</form>
					</div>
					<ul class="navbar-nav ms-auto mb-2 mb-lg-0">
						<li class="nav-item dropdown navigation__item account-service">
							<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
							   data-bs-toggle="dropdown" aria-expanded="false">
								<p class="navigation__text">こんにちは、{{ request.user.last_name }}</p>
								<p class="navigation__text">アカウントサービス</p>
							</a>
							<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
								<li><a class="dropdown-item" href="{% url 'quote:mypage' %}">マイページ</a></li>
								<li><a class="dropdown-item" href="{% url 'admin:index' %}">Admin Page</a></li>
								{% if user.is_superuser %}
									<li><a class="dropdown-item" href="{% url 'stock:get_data' %}">GET DATA</a></li>
								{% endif %}
								<li>
									<hr class="dropdown-divider">
								</li>
								<li>
									<a class="dropdown-item" href="{% url 'admin:logout' %}">
										<i class="fa-solid fa-right-from-bracket"></i>
										ログアウト
									</a>
								</li>
							</ul>
						</li>
					</ul>
					<ul class="navbar-nav mb-2 mb-lg-0">
						<li class="nav-item navigation__item">
{#							<a class="nav-link" href="{% url 'stock:my_order_info' %}">#}
{#								<p class="navigation__cancel">キャンセルもこちら</p>#}
{#								<p class="navigation__text">注文履歴</p>#}
{#							</a>#}
							<a class="nav-link" href="{% url 'quote:orderinfo' %}">
								<p class="navigation__cancel">全体の履歴はこちら</p>
								<p class="navigation__text">見積履歴</p>
							</a>
						</li>
						<li class="nav-item navigation__item">
{#							<a class="nav-link" href="{% url 'stock:cart' %}">#}
{#								<span class="navigation__text cart-icon"><i class="fa-solid fa-cart-shopping"></i></span>#}
{#								<span class="navigation__text">カート</span>#}
{#							</a>#}
							<a class="nav-link" href="{% url 'quote:item_list' %}">
								<p class="navigation__text">見積もりカート</p>
								<span class="navigation__text cart-icon">
									<i class="fa-solid fa-cart-shopping shopping-cart"></i>
									{% item_count request.user as item_count%}
									{% if item_count > 0 %}
										<span class="badge rounded-pill bg-danger">{% item_count request.user %}</span>
									{% endif %}
								</span>
							</a>
						</li>
					</ul>
				</div>
			</div>
		</nav>

		<div class="page-wrapper chiller-theme">
			<div class="main-contents">
				{% block content %}
				{% endblock %}
			</div>
		</div>

		<footer class="footer appear up">
			<div class="footer__nav">
				<ul class="footer__ul">
					<li class="footer__li item">
						<a href="{% url 'quote:mypage' %}">マイページ</a>
					</li>
					<li class="footer__li item">
						<a href="{% url 'stock:construction' %}">FAQ</a>
					</li>
					<li class="footer__li item">
						<a href="{% url 'stock:construction' %}">お問い合わせ</a>
					</li>
					<li class="footer__li item">
						<a href="{% url 'admin:logout' %}">ログアウト</a>
					</li>
				</ul>
			</div>
		</footer>
	</div>

	{% bootstrap_javascript %}
	<script src="https://unpkg.com/swiper@8/swiper-bundle.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
	        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
	        crossorigin="anonymous"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
	        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
	        crossorigin="anonymous"></script>
	<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
	        crossorigin="anonymous"></script>
	<script src="{% static 'js/vendors/jquery.bootstrap.modal.forms.min.js' %}"></script>
	<script src="{% static 'js/vendors/scroll-polyfill.js' %}"></script>
	<script src="{% static 'js/libs/scroll.js' %}"></script>
	<script src="{% static 'js/libs/hero-slider.js' %}"></script>
	<script src="{% static 'js/modules/functions.js' %}"></script>
	<script src="{% static 'js/stock/stock.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
	{% block javascript %}
	{% endblock %}
	<script type="text/javascript">
		modal_form('.requester-update', "{% url 'user:requester_update' user.pk %}");
	</script>
</body>

</html>

templates/construction.html
{% extends 'base.html' %}

{% block content %}

	<div class="container mt-5">
		<div class="row">
			<div class="col-8 offset-2">
				<h1>工事中です</h1>
				<h1>
					<a href="{% url 'stock:top' %}"><i class="fa-solid fa-arrow-circle-left"></i>TOPに戻る</a>
				</h1>
				<img src="../media/images/popuko.png" alt="kaisou" class="construction">
			</div>
		</div>
	</div>

{% endblock content %}

templates/pagination.html
{% load extras %}


{% if page_obj.has_other_pages %}
        <ul class="pagination">
            {% if page_obj.has_previous %}
	            <li class="page-item pagination-prev">
	                <a class="page-link text-primary" href="?{% url_replace request 'page' page_obj.previous_page_number %}">&laquo;</a>
	            </li>
            {% endif %}

            {% if page_obj.has_previous %}
                {% if page_obj.previous_page_number != 1 %}
                    <li class="page-item">
	                    <a class="page-link text-primary" href="?{% url_replace request 'page' 1 %}">1</a>
                    </li>
	                {% if page_obj.previous_page_number > 2 %}
	                    <li>…</li>
	                {% endif %}
                {% endif %}
                <li class="page-item">
	                <a class="page-link text-primary" href="?page={{ page_obj.previous_page_number }}">
		                {{ page_obj.previous_page_number }}
	                </a>
                </li>
            {% endif %}
            <li class="active page-item">
	            <span class="page-link text-secondary">
		            {{ page_obj.number }}
		            <span class="page-link sr-only">(current)</span>
	            </span>
            </li>
            {% if page_obj.has_next %}
                <li class="page-item">
	                <a class="page-link text-primary " href="?page={{ page_obj.next_page_number }}">
		                {{ page_obj.next_page_number }}
	                </a>
                </li>
                {% if page_obj.next_page_number != page_obj.paginator.num_pages %}
                    <li>…</li>
                    <li>
	                    <a class="page-link text-primary" href="?page={{ page_obj.paginator.num_pages }}">
		                    {{ page_obj.paginator.num_pages }}
	                    </a>
                    </li>
                {% endif %}
            {% endif %}
            {% if page_obj.has_next %}
	            <li class="page-item">
		            <a class="page-link text-primary" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
	            </li>
            {% endif %}
        </ul>
{% endif %}

templates/top.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}

	<div class="content">
		<div class="hero">
			<div class="swiper top-swiper">
				<div class="swiper-wrapper">
					<div class="swiper-slide">
						<img src="media/images/notepc1.jpg" alt="notepc1">
					</div>
					<div class="swiper-slide">
						<img src="media/images/notepc2.jpg" alt="notepc2">
					</div>
					<div class="swiper-slide">
						<img src="media/images/notepc3.jpg" alt="notepc3">
					</div>
					<div class="swiper-slide">
						<img src="media/images/notepc4.jpeg" alt="notepc4">
					</div>
				</div>
			</div>
		</div>
		<section class="container select">
			<div class="row">
				<div class="card select__card quote">
					<div class="card-body">
						<span>見積もり依頼</span>
						<img src="media/images/quote.jpg" alt="" class="quote">
					</div>
				</div>
				<div class="card select__card stock">
					<div class="card-body">
						<span>貯蔵品確認</span>
						<img src="media/images/stock.jpg" alt="">
					</div>
				</div>
			</div>
{#			<i class="fa-solid fa-right"></i>#}
{#			<a href="{% url 'stock:orderinfo_list' %}" class="select__admin float-end mt-3">#}
{#				<i class="fa-solid fa-arrow-right-long-to-line"></i>#}
{#				管理者の方はこちら#}
{#			</a>#}
		</section>
	</div>

{% endblock content %}

{% block javascript %}

	<script type="text/javascript">
		const quote = document.querySelector('.quote');
		const quoteUrl = "{% url 'quote:genre' %}";
		const stock = document.querySelector('.stock');
		const stockUrl = "{% url 'stock:storage_list_admin' %}";
		linkClick(stock, stockUrl);
		linkClick(quote, quoteUrl);
	</script>
{% endblock javascript %}