stock/urls.py
from django.urls import path
from rest_framework import routers

from . import views

app_name = 'stock'

router = routers.DefaultRouter()
router.register(r'option', views.OptionViewSet)
router.register(r'storage', views.StorageItemViewSet)
router.register(r'kittingPlan', views.KittingPlanViewSet)
router.register(r'orderItem', views.OrderItemViewSet)
router.register(r'storageCart', views.StorageCartViewSet)
router.register(r'approve', views.ApproveViewSet)
router.register(r'orderInfo', views.OrderInfoViewSet)

urlpatterns = [
	path('', views.top_page, name='top'),
	path('construction', views.construction, name='construction'),
	path('item_list', views.StorageItemListView.as_view(), name='storage_list'),
	path('item_list_admin', views.StorageItemAdminListView.as_view(), name='storage_list_admin'),
	path('detail/<int:pk>', views.StorageItemDetailView.as_view(), name='storage_detail'),
	path('detail_admin/<int:pk>', views.StorageItemDetailAdminView.as_view(), name='storage_detail_admin'),
	path('get_data/', views.create_storage_data, name='get_data'),
	path('create/', views.StorageItemCreateView.as_view(), name='storage_create'),
	path('update/<int:pk>', views.StorageItemUpdateView.as_view(), name='storage_update'),
	path('optionCreate/', views.OptionCreateView.as_view(), name='option_create'),
	path('cart/', views.StorageCartView.as_view(), name='cart'),
	path('add_item/<int:pk>', views.add_item, name='add_item'),
	path('reduce_item/<int:pk>', views.reduce_cart, name='reduce_cart'),
	path('remove_item/<int:pk>', views.remove_cart, name='remove_cart'),
	path('approve/', views.ApproveView.as_view(), name='approve'),
	path('approve_create/', views.ApproveCreateView.as_view(), name='approve_create'),
	path('approve_update/<int:pk>', views.ApproveUpdateView.as_view(), name='approve_update'),
	path('add_orderInfo/', views.add_order_info, name='add_order_info'),
	path('confirm/<int:pk>', views.ConfirmView.as_view(), name='confirm'),
	path('my_order_info/', views.MyOrderInfoView.as_view(), name='my_order_info'),
	path('order_info_list/', views.OrderInfoListView.as_view(), name='orderinfo_list'),
	path('order_info_update/<int:pk>', views.OrderInfoUpdateView.as_view(), name='orderinfo_update'),
	path('order_info_detail/<int:pk>', views.OrderInfoDetailView.as_view(), name='orderinfo_detail'),
	path('order_info_detail_admin/<int:pk>', views.OrderInfoDetailAdminView.as_view(), name='orderinfo_detail_admin'),
	path('order_info_delete_select/<int:pk>', views.OrderInfoSelectView.as_view(), name='delete_select'),
	path('order_info_status/<int:pk>', views.order_info_status_view, name='orderinfo_status'),
	path('chang_quantity/<int:pk>', views.ChangeQuantity.as_view(), name='change_quantity'),
]

user/urls.py
from django.urls import path
from rest_framework import routers

from . import views

app_name = 'user'

router = routers.DefaultRouter()
router.register(r'base', views.BaseViewSet)
router.register(r'room', views.RoomViewSet)
router.register(r'requester', views.RequesterViewSet)

urlpatterns = [
	path('requester/<int:pk>', views.RequesterUpdateView.as_view(), name='requester_update')
]

stock/models.py
from django.db import models
from django.utils import timezone

import datetime

from device.models import PCDetail
from user.models import User, Base, Requester


class BaseManager(models.Manager):
    def get_or_none(self, **kwargs):
        try:
            return self.get_queryset().get(**kwargs)
        except self.model.DoesNotExist:
            return None


class Option(models.Model):
    maker = models.CharField(
        verbose_name='メーカー',
        max_length=100
    )
    
    name = models.CharField(
        verbose_name='製品名',
        max_length=200
    )
    
    price = models.PositiveIntegerField(
        verbose_name='金額(円)'
    )
    
    quantity = models.PositiveSmallIntegerField(
        verbose_name='在庫数'
    )
    
    remarks = models.TextField(
        verbose_name='備考',
        null=True,
        blank=True
    )
    
    def __str__(self):
        return f'{self.maker}{self.name}'
    
    class Meta:
        verbose_name = '付属品'
        verbose_name_plural = '付属品'


class StorageItem(models.Model):
    objects = BaseManager()
    
    order_number = models.CharField(
        verbose_name='発注番号',
        max_length=100
    )
    
    item = models.ForeignKey(
        PCDetail,
        on_delete=models.CASCADE,
        verbose_name='在庫PC'
    )
    
    price = models.PositiveIntegerField(
        verbose_name='本体価格'
    )
    
    quantity = models.PositiveSmallIntegerField(
        verbose_name='在庫数',
        null=True,
        blank=True
    )
    
    option = models.ManyToManyField(
        Option,
        verbose_name='付属品',
        blank=True
    )
    
    total_price = models.PositiveIntegerField(
        verbose_name='合計金額',
        null=True,
        blank=True
    )
    
    base = models.ForeignKey(
        Base,
        on_delete=models.CASCADE,
        verbose_name='在庫拠点',
    )
    
    registration_at = models.DateField(
        verbose_name='登録日',
        null=True,
        blank=True
    )
    
    remarks = models.TextField(
        verbose_name='備考',
        null=True,
        blank=True
    )
    
    def save(self, *args, **kwargs):
        if self.registration_at is None and not self.id:
            self.registration_at = timezone.now()
        self.total_price = self.price
        super(StorageItem, self).save(*args, **kwargs)
        if self.id is not None:
            for option in self.option.all():
                self.total_price += option.price
        super(StorageItem, self).save(*args, **kwargs)
    
    def __str__(self):
        return f'{self.item} ({self.base})'
    
    class Meta:
        verbose_name = '貯蔵品'
        verbose_name_plural = '貯蔵品'


class KittingPlan(models.Model):
    objects = BaseManager()
    
    kitting_choice = (
        ('標準', '標準'),
        ('お急ぎ便', 'お急ぎ便')
    )
    name = models.CharField(
        verbose_name='プラン名',
        max_length=10,
        choices=kitting_choice,
        default='標準'
    )
    
    price = models.PositiveSmallIntegerField(
        verbose_name='金額',
    )
    
    due = models.PositiveSmallIntegerField(
        verbose_name='納期',
        default=7
    )
    
    def __str__(self):
        return f'{self.name} {self.price}円'
    
    class Meta:
        verbose_name = 'キッティング価格'
        verbose_name_plural = 'キッティング価格'


class OrderItem(models.Model):
    objects = BaseManager()
    
    storage_item = models.ForeignKey(
        StorageItem,
        on_delete=models.CASCADE,
        verbose_name='貯蔵品'
    )
    
    quantity = models.PositiveSmallIntegerField(
        verbose_name='数量',
        default=1
    )
    
    ordered = models.BooleanField(
        verbose_name='確保済み',
        default=False
    )
    
    kitting_plan = models.ForeignKey(
        KittingPlan,
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    
    price = models.PositiveIntegerField(
        verbose_name='合計金額',
        null=True,
        blank=True
    )
    
    due_at = models.DateField(
        verbose_name='納品予定日',
        null=True,
        blank=True
    )
    
    requester = models.ForeignKey(
        Requester,
        on_delete=models.CASCADE,
        verbose_name='依頼者',
    )
    
    def save(self, *args, **kwargs):
        item_price = self.storage_item.total_price
        price = item_price * self.quantity
        kitting_plan = self.kitting_plan
        if kitting_plan is not None:
            now = datetime.datetime.now()
            hour = now.hour
            day = kitting_plan.due
            over_day = day + 1
            if hour >= 17:
                date = datetime.date.today() + datetime.timedelta(days=over_day)
            else:
                date = datetime.date.today() + datetime.timedelta(days=day)
            self.due_at = date
            self.price = price + kitting_plan.price
        else:
            self.price = price
        super(OrderItem, self).save(*args, **kwargs)
    
    def __str__(self):
        return f'{self.storage_item} × {self.quantity}'
    
    class Meta:
        verbose_name = '確保アイテム'
        verbose_name_plural = '確保アイテム'


class StorageCart(models.Model):
    objects = BaseManager()
    
    requester = models.ForeignKey(
        Requester,
        on_delete=models.CASCADE,
        verbose_name='依頼者'
    )
    
    order_item = models.ManyToManyField(
        OrderItem,
        verbose_name='確保アイテム',
    )
    
    price = models.PositiveIntegerField(
        verbose_name='合計金額（税込み）',
        null=True,
        blank=True
    )
    
    tax_price = models.PositiveSmallIntegerField(
        verbose_name='消費税',
        null=True,
        blank=True
    )
    
    ordered = models.BooleanField(
        default=False
    )
    
    def save(self, *args, **kwargs):
        if self.pk is not None:
            self.price = 0
            subtotal = 0
            tax = 0.1
            self.tax_price = 0
            for item in self.order_item.all():
                subtotal += item.storage_item.total_price * item.quantity
                if item.kitting_plan is not None:
                    subtotal += item.kitting_plan.price
            self.tax_price += round(subtotal * tax)
            self.price += subtotal + self.tax_price
        super(StorageCart, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.requester.user.screenname
    
    class Meta:
        verbose_name = '貯蔵品カート'
        verbose_name_plural = '貯蔵品カート'


class Approve(models.Model):
    last_name = models.CharField(
        verbose_name='姓',
        max_length=32
    )
    
    first_name = models.CharField(
        verbose_name='名',
        max_length=32,
    )
    
    dept_code = models.PositiveSmallIntegerField(
        verbose_name='部門コード'
    )
    
    dept_name = models.CharField(
        verbose_name='部門名',
        max_length=255
    )
    
    requester = models.ForeignKey(
        Requester,
        on_delete=models.CASCADE,
        verbose_name='依頼者',
        null=True,
        blank=True
    )
    
    def __str__(self):
        return f'{self.last_name} {self.first_name}'
    
    class Meta:
        verbose_name = '承認者情報'
        verbose_name_plural = '承認者情報'


class OrderInfo(models.Model):
    status_choices = (
        ('1', '準備中'),
        ('2', '確保済み'),
        ('3', 'キッティング中'),
        ('4', 'キッティング完了'),
        ('5', '納品済み')
    )
    
    objects = BaseManager()
    
    status = models.CharField(
        verbose_name='ステータス',
        max_length=2,
        choices=status_choices,
        default=1
    )
    
    number = models.CharField(
        verbose_name='受注番号',
        max_length=100
    )
    
    ticket = models.PositiveIntegerField(
        verbose_name='チケット番号',
        null=True,
        blank=True
    )
    
    storage_cart = models.ForeignKey(
        StorageCart,
        on_delete=models.CASCADE,
        verbose_name='カート'
    )
    
    approve = models.ForeignKey(
        Approve,
        on_delete=models.CASCADE,
        verbose_name='承認者情報'
    )
    
    requester = models.ForeignKey(
        Requester,
        on_delete=models.CASCADE,
        verbose_name='依頼者'
    )
    
    contact_user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='担当者',
        null=True,
        blank=True,
        related_name='contact_user'
    )
    
    ordered_at = models.DateTimeField(
        verbose_name='依頼日',
        null=True,
        blank=True
    )
    
    updated_at = models.DateTimeField(
        verbose_name='更新日',
        null=True,
        blank=True
    )
    
    completed_delivery = models.BooleanField(
        verbose_name='納品済み',
        default=False
    )
    
    delivery_at = models.DateTimeField(
        verbose_name='納品日',
        null=True,
        blank=True
    )
    
    due_at = models.DateField(
        verbose_name='納品予定日',
        null=True,
        blank=True
    )
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.ordered_at = timezone.now()
        self.updated_at = timezone.now()
        if self.delivery_at is not None:
            self.completed_delivery = True
        due = []
        for item in self.storage_cart.order_item.all():
            due.append(item.due_at)
        due.sort()
        self.due_at = due[-1]
        super(OrderInfo, self).save(*args, **kwargs)
    
    def __str__(self):
        return f'{self.number}'
    
    class Meta:
        verbose_name = '依頼内容'
        verbose_name_plural = '依頼内容'

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils.translation import gettext_lazy as _
from django.dispatch import receiver


class UserManager(BaseUserManager):
	use_in_migrations = True

	def _create_user(self, username, password, is_superuser, **extra_fields):
		if not username:
			raise ValueError('The given username must be set')
		username = self.model.normalize_username(username)
		user = self.model(username=username, is_superuser=is_superuser, **extra_fields)
		user.set_password(password)
		user.save(using=self.db)
		return user

	def create_superuser(self, username, password, **extra_fields):
		return self._create_user(username, password, True, **extra_fields)


# 独自ユーザーモデルの作成
class User(AbstractBaseUser, PermissionsMixin):
	user_vali = UnicodeUsernameValidator()
	username = models.CharField(
		verbose_name='社員番号',
		max_length=200,
		unique=True,
		validators=[user_vali]
	)
	screenname = models.CharField(
		verbose_name='氏名',
		max_length=200,
		blank=True,
	)
	first_name = models.CharField(
		_('first name'),
		max_length=100,
		blank=True,
	)
	last_name = models.CharField(
		_('last name'),
		max_length=100,
		blank=True,
	)
	department = models.CharField(
		verbose_name='部署',
		max_length=255,
		default='[]'
	)
	email = models.EmailField(
		_('email address'),
		blank=True,
	)
	is_staff = models.BooleanField(
		_('staff status'),
		default=False,
	)
	is_active = models.BooleanField(
		_('active'),
		default=True,
	)
	created_date = models.DateTimeField(
		verbose_name='登録日時',
		auto_now_add=True,
	)
	objects = UserManager()
	USERNAME_FIELD = 'username'

	def __str__(self):
		return self.screenname

	def get_full_name(self):
		full_name = '%s %s' % (self.first_name, self.last_name)
		return full_name

	def get_short_name(self):
		return self.last_name

	# def save(self, *args, **kwargs):
	# 	Requester.objects.update_or_create(user_id=self.pk)
	# 	super(User, self).save(*args, **kwargs)

	class Meta:
		verbose_name = _('user')
		verbose_name_plural = _('user')


class Group(models.Model):
	name = models.CharField(
		verbose_name='グループ名',
		max_length=255,
		unique=True
	)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = 'グループ'
		verbose_name_plural = 'グループ'


class Member(models.Model):
	group = models.ForeignKey(
		Group,
		on_delete=models.CASCADE,
		verbose_name='所属グループ'
	)

	user = models.ForeignKey(
		User,
		on_delete=models.CASCADE,
		verbose_name='ユーザー'
	)

	def __str__(self):
		return f'{self.group.name}: {self.user}'

	class Meta:
		verbose_name = 'メンバー'
		verbose_name_plural = 'メンバー'


class Base(models.Model):
	name = models.CharField(
		verbose_name='拠点名',
		max_length=50
	)

	def __str__(self):
		return self.name

	class Meta:
		verbose_name = '拠点'
		verbose_name_plural = '拠点'


class Room(models.Model):
	name = models.CharField(
		verbose_name='ルーム',
		max_length=100
	)

	base = models.ForeignKey(
		Base,
		on_delete=models.CASCADE,
		verbose_name='拠点'
	)

	def __str__(self):
		return f'{self.base} {self.name}'

	class Meta:
		verbose_name = 'ルーム'
		verbose_name_plural = 'ルーム'


class Requester(models.Model):
	user = models.ForeignKey(
		User,
		on_delete=models.CASCADE,
		verbose_name='依頼者'
	)

	room = models.ForeignKey(
		Room,
		on_delete=models.CASCADE,
		verbose_name='ルーム',
		null=True,
		blank=True
	)

	def __str__(self):
		return self.user.screenname

	class Meta:
		verbose_name = '依頼者'
		verbose_name_plural = '依頼者'


@receiver(models.signals.post_save, sender=User)
def post_save_user_signal_handler(sender, instance, created, **kwargs):
	if created:
		group, create = Group.objects.get_or_create(name='一般ユーザー')
		Member.objects.create(
			group=group,
			user=instance
		)

templates/stock/storage_item/detail.html
{% extends "base.html" %}
{% load static %}
{% load django_bootstrap5 %}
{% load humanize %}
{% load extras %}

{% block content %}

    <div class="container">
        <div class="row mt-5">
            <div class="col-md-4">
                {% if storageitem.item.pc.img.name == '' %}
                    <img src="/media/images/no_image_logo.png" alt="noimage" class="detail-img">
                {% else %}
                    <img src="{{ storageitem.item.pc.img.url }}" alt="{{ storageitem.item.pc.name }}" class="detail-img">
                {% endif %}
            </div>
            <div class="col-md-5 offset-3">
                <div class="row">
                    <h4 class="detail-item">{{ storageitem.item.pc.maker }}</h4>
                    <h4 class="detail-item">{{ storageitem.item.pc.name }}</h4>
                </div>
                <div class="row mt-3">
                    <p>在庫拠点：{{ storageitem.base.name }}</p>
                    <p>在庫数：{{ storageitem.quantity }}</p>
                    <p>本体価格：{{ storageitem.price | intcomma }}</p>
                    <p>付属品：</p>
                    {% for option in storageitem.option.all %}
                        <p>{{ option.maker }} {{ option.name }} {{ option.price | intcomma}}円</p>
                        {% empty %}
                        <p>なし</p>
                    {% endfor %}
                </div>
                <div class="row mt-3">
                    <p>合計金額：{{ storageitem.total_price | intcomma }}円</p>
                </div>
                <div class="row mt-3">
                    <button type="button" class="btn btn-warning" onclick="location.href='{% url "stock:add_item" storageitem.pk %}'">
                        <span>
                            <i class="fas fa-cart-arrow-down"></i>注文する
                        </span>
                    </button>
                </div>
            </div>
        </div>

        <div class="row mt-5">
            <div class="col-9 offset-1">
                <table class="table detail-table">
                    <thead class="table-light">
                        <tr>
                            <th class="spec-header" colspan="2">スペック</th>
                        </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td class="td-spec">CPU</td>
                        <td>{{ storageitem.item.cpu }}</td>
                    </tr>
                    <tr>
                        <td class="td-spec">メモリー</td>
                        <td>{{ storageitem.item.memory }}GB</td>
                    </tr>
                    <tr>
                        <td class="td-spec">ストレージタイプ</td>
                        <td>{{ storageitem.item.storage.get_type_display }}</td>
                    </tr>
                    <tr>
                        <td class="td-spec">ストレージ容量</td>
                        <td>{{ storageitem.item.storage.size }}GB</td>
                    </tr>
                    <tr>
                        <td class="td-spec">サイズ</td>
                        <td>{{ storageitem.item.size }}インチ</td>
                    </tr>
                    <tr>
                        <td class="td-spec">webカメラ</td>
                        <td>
	                        <input type="checkbox" class="form-check-input" id="cameraCheck" aria-label="camera"
	                               {% if storageitem.item.camera %}checked{% endif %} disabled>
                        </td>
                    </tr>
                    <tr>
                        <td class="td-spec">指紋認証</td>
                        <td>
                            <input type="checkbox" class="form-check-input" id="fingerprintCheck" aria-label="fingerprint"
                                   {% if storageitem.item.fingerprint %}checked{% endif %} disabled>
                        </td>
                    </tr>
                    <tr>
                        <td class="td-spec">テンキー</td>
                        <td>
                            <input type="checkbox" class="form-check-input" id="numpadCheck" aria-label="numpad"
                                   {% if storageitem.item.numpad %}checked{% endif %} disabled>
                        </td>
                    </tr>
                    <tr>
                        <td class="td-spec">有線LANポート</td>
                        <td>
                            <input type="checkbox" class="form-check-input" id="lanCheck" aria-label="lan"
                                   {% if storageitem.item.lan %}checked{% endif %} disabled>
                        </td>
                    </tr>
                    <tr>
                        <td class="td-spec">USBポート数</td>
                        <td>
	                        {% if storageitem.item.usb %}
                                {{ storageitem.item.usb }}
                            {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td class="td-spec">HDMI</td>
                        <td>
	                        {% if storageitem.item.hdmi %}
	                            {{ storageitem.item.hdmi }}
	                        {% endif %}
                        </td>
                    </tr>
                    <tr>
                        <td class="td-spec">VGA</td>
                        <td>
	                        {% if storageitem.item.vga %}
	                            {{ storageitem.item.vga }}
	                        {% endif %}
                        </td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="row my-3">
            <div class="col-9 offset-1">
                <a href="{% url 'stock:storage_list' %}">
                    <i class="fas fa-undo-alt"></i>戻る
                </a>
            </div>
        </div>
    </div>

{% endblock content %}

{% block javascript %}
    <script type="text/javascript">

    </script>

{% endblock javascript %}

templates/stock/storage_item/list.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load static %}
{% load humanize %}
{% load extras %}


{% block content %}

    <div class="container my-5">
        <div class="modal fade" tabindex="-1" role="dialog" id="modal" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content"></div>
            </div>
        </div>
        <div class="row mb-3">
            <h2 class="title-text">在庫リスト</h2>
        </div>
        <div class="row mt-5">
            <div class="form-group col-2">
            <label>在庫拠点：</label>
            <select title="base" name="base" class="custom-select" id="baseSelect">
                <option value="all">すべて</option>
                {% for base in base_list %}
                    <option value="{{ base.name }}">{{ base.name }}</option>
                {% endfor %}
            </select>
            </div>
            <div class="form-group col-3">
            <label>カテゴリー：</label>
            <select title="category" name="category" class="custom-select" id="categorySelect">
                <option value="all">すべて</option>
                <option value="ノートPC">ノートPC</option>
                <option value="デスクトップPC">デスクトップPC</option>
                <option value="ミニPC">ミニPC</option>
            </select>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-4 item-list">
                <i class="fas fa-list item-table"></i>
                <i class="fas fa-table item-card ms-3"></i>
            </div>
        </div>
        <section class="row" id="storageTable">
            <div class="storage-table">
                {% include 'stock/modules/item_list_table.html' %}
            </div>
        </section>
        <!-- カード表示 -->
        <section class="row" id="storageCard">
            {% include 'stock/modules/item_list_card.html' %}
        </section>
        <div class="row mt-5">
	        {% include 'pagination.html' %}
        </div>
    </div>


{% endblock content %}

{% block javascript %}

    <script type="text/javascript">
        {% for storageitem in storageitem_list %}
            let get_table_{{ storageitem.pk }} = document.querySelector('#table{{ storageitem.pk }}');
            let get_card_{{ storageitem.pk }} = document.querySelector('#storageCard{{ storageitem.pk }}');
            get_table_{{ storageitem.pk }}.onclick = function() {
                location.href = '{% url "stock:storage_detail" storageitem.pk %}';
            }
            get_card_{{ storageitem.pk }}.onclick = function() {
                location.href = '{% url "stock:storage_detail" storageitem.pk %}'
            }
        {% endfor %}


        $(function() {
            $('#baseSelect').change(function() {
                let val = $(this).val();
                let categorySelect = $('#categorySelect').val();
                {% for storageitem in storageitem_list %}
                    let base_{{ storageitem.pk }} = document.querySelector('#base{{ storageitem.pk }}');
                    let base_val_{{ storageitem.pk }} = base_{{ storageitem.pk }}.textContent;
                    let category{{ storageitem.pk }} = document.querySelector('#category{{ storageitem.pk }}');
                    let category_val{{ storageitem.pk }} = category{{ storageitem.pk }}.textContent;
                    if (categorySelect === category_val{{ storageitem.pk }}) {
                       if (val === base_val_{{ storageitem.pk }}) {
                            $('#table{{ storageitem.pk }}').show();
                            $('#card{{ storageitem.pk }}').show();
                        } else if (val === 'all') {
                            $('#table{{ storageitem.pk }}').show();
                            $('#card{{ storageitem.pk }}').show();
                        } else {
                            $('#table{{ storageitem.pk }}').hide();
                            $('#card{{ storageitem.pk }}').hide();
                        }
                    } else if (categorySelect === 'all'){
                        if (val === base_val_{{ storageitem.pk }}) {
                            $('#table{{ storageitem.pk }}').show();
                            $('#card{{ storageitem.pk }}').show();
                        } else if (val === 'all') {
                            $('#table{{ storageitem.pk }}').show();
                            $('#card{{ storageitem.pk }}').show();
                        } else {
                            $('#table{{ storageitem.pk }}').hide();
                            $('#card{{ storageitem.pk }}').hide();
                        }
                    } else {
                        $('#table{{ storageitem.pk }}').hide();
                        $('#card{{ storageitem.pk }}').hide();
                    }
                {% endfor %}
            });
        });

        $(function() {
            $('#categorySelect').change(function() {
                let val = $(this).val();
                let baseSelect = $('#baseSelect').val();
                {% for storageitem in storageitem_list %}
                    let category{{ storageitem.pk }} = document.querySelector('#category{{ storageitem.pk }}');
                    let category_val{{ storageitem.pk }} = category{{ storageitem.pk }}.textContent;
                    let base_{{ storageitem.pk }} = document.querySelector('#base{{ storageitem.pk }}');
                    let base_val_{{ storageitem.pk }} = base_{{ storageitem.pk }}.textContent;
                    if (baseSelect === base_val_{{ storageitem.pk }}) {
                        if (val === category_val{{ storageitem.pk }}) {
                            $('#table{{ storageitem.pk }}').show();
                            $('#card{{ storageitem.pk }}').show();
                        } else if(val === 'all') {
                            $('#table{{ storageitem.pk }}').show();
                            $('#card{{ storageitem.pk }}').show();
                        }else {
                            $('#table{{ storageitem.pk }}').hide();
                            $('#card{{ storageitem.pk }}').hide();
                        }
                    } else if (baseSelect === 'all') {
                        if (val === category_val{{ storageitem.pk }}) {
                            $('#table{{ storageitem.pk }}').show();
                            $('#card{{ storageitem.pk }}').show();
                        } else if(val === 'all') {
                            $('#table{{ storageitem.pk }}').show();
                            $('#card{{ storageitem.pk }}').show();
                        }else {
                            $('#table{{ storageitem.pk }}').hide();
                            $('#card{{ storageitem.pk }}').hide();
                        }
                    } else {
                        $('#table{{ storageitem.pk }}').hide();
                        $('#card{{ storageitem.pk }}').hide();
                    }
                {% endfor %}
            });
        });

        let listBtn = document.querySelector('.item-table');
        let cardBtn = document.querySelector('.item-card');
        let storageTable = document.querySelector('#storageTable');
        let storageCard = document.querySelector('#storageCard');

        let changeTable = (table, card) => {
            table.style.display = '';
            card.style.display = 'none';
        }

        let changeCard = (table, card) => {
            table.style.display = 'none';
            card.style.display = '';
        }

        listBtn.addEventListener('click', ()=> {
            changeTable(storageTable, storageCard);
        }, false);

        cardBtn.addEventListener('click', ()=> {
            changeCard(storageTable, storageCard);
        }, false);

    </script>

{% endblock javascript %}