stock/urls.py
from django.urls import path
from rest_framework import routers

from . import views

app_name = 'stock'

router = routers.DefaultRouter()
router.register(r'option', views.OptionViewSet)
router.register(r'storage', views.StorageItemViewSet)
router.register(r'kittingPlan', views.KittingPlanViewSet)
router.register(r'orderItem', views.OrderItemViewSet)
router.register(r'storageCart', views.StorageCartViewSet)
router.register(r'approve', views.ApproveViewSet)
router.register(r'orderInfo', views.OrderInfoViewSet)

urlpatterns = [
	path('', views.top_page, name='top'),
	path('construction', views.construction, name='construction'),
	path('item_list', views.StorageItemListView.as_view(), name='storage_list'),
	path('item_list_admin', views.StorageItemAdminListView.as_view(), name='storage_list_admin'),
	path('detail/<int:pk>', views.StorageItemDetailView.as_view(), name='storage_detail'),
	path('detail_admin/<int:pk>', views.StorageItemDetailAdminView.as_view(), name='storage_detail_admin'),
	path('get_data/', views.create_storage_data, name='get_data'),
	path('create/', views.StorageItemCreateView.as_view(), name='storage_create'),
	path('update/<int:pk>', views.StorageItemUpdateView.as_view(), name='storage_update'),
	path('optionCreate/', views.OptionCreateView.as_view(), name='option_create'),
	path('cart/', views.StorageCartView.as_view(), name='cart'),
	path('add_item/<int:pk>', views.add_item, name='add_item'),
	path('reduce_item/<int:pk>', views.reduce_cart, name='reduce_cart'),
	path('remove_item/<int:pk>', views.remove_cart, name='remove_cart'),
	path('approve/', views.ApproveView.as_view(), name='approve'),
	path('approve_create/', views.ApproveCreateView.as_view(), name='approve_create'),
	path('approve_update/<int:pk>', views.ApproveUpdateView.as_view(), name='approve_update'),
	path('add_orderInfo/', views.add_order_info, name='add_order_info'),
	path('confirm/<int:pk>', views.ConfirmView.as_view(), name='confirm'),
	path('my_order_info/', views.MyOrderInfoView.as_view(), name='my_order_info'),
	path('order_info_list/', views.OrderInfoListView.as_view(), name='orderinfo_list'),
	path('order_info_update/<int:pk>', views.OrderInfoUpdateView.as_view(), name='orderinfo_update'),
	path('order_info_detail/<int:pk>', views.OrderInfoDetailView.as_view(), name='orderinfo_detail'),
	path('order_info_detail_admin/<int:pk>', views.OrderInfoDetailAdminView.as_view(), name='orderinfo_detail_admin'),
	path('order_info_delete_select/<int:pk>', views.OrderInfoSelectView.as_view(), name='delete_select'),
	path('order_info_status/<int:pk>', views.order_info_status_view, name='orderinfo_status'),
	path('chang_quantity/<int:pk>', views.ChangeQuantity.as_view(), name='change_quantity'),
]

user/urls.py
from django.urls import path
from rest_framework import routers

from . import views

app_name = 'user'

router = routers.DefaultRouter()
router.register(r'base', views.BaseViewSet)
router.register(r'room', views.RoomViewSet)
router.register(r'requester', views.RequesterViewSet)

urlpatterns = [
	path('requester/<int:pk>', views.RequesterUpdateView.as_view(), name='requester_update')
]

stock/models.py
from django.db import models
from django.utils import timezone

import datetime

from device.models import PCDetail
from user.models import User, Base, Requester


class BaseManager(models.Manager):
    def get_or_none(self, **kwargs):
        try:
            return self.get_queryset().get(**kwargs)
        except self.model.DoesNotExist:
            return None


class Option(models.Model):
    maker = models.CharField(
        verbose_name='メーカー',
        max_length=100
    )
    
    name = models.CharField(
        verbose_name='製品名',
        max_length=200
    )
    
    price = models.PositiveIntegerField(
        verbose_name='金額(円)'
    )
    
    quantity = models.PositiveSmallIntegerField(
        verbose_name='在庫数'
    )
    
    remarks = models.TextField(
        verbose_name='備考',
        null=True,
        blank=True
    )
    
    def __str__(self):
        return f'{self.maker}{self.name}'
    
    class Meta:
        verbose_name = '付属品'
        verbose_name_plural = '付属品'


class StorageItem(models.Model):
    objects = BaseManager()
    
    order_number = models.CharField(
        verbose_name='発注番号',
        max_length=100
    )
    
    item = models.ForeignKey(
        PCDetail,
        on_delete=models.CASCADE,
        verbose_name='在庫PC'
    )
    
    price = models.PositiveIntegerField(
        verbose_name='本体価格'
    )
    
    quantity = models.PositiveSmallIntegerField(
        verbose_name='在庫数',
        null=True,
        blank=True
    )
    
    option = models.ManyToManyField(
        Option,
        verbose_name='付属品',
        blank=True
    )
    
    total_price = models.PositiveIntegerField(
        verbose_name='合計金額',
        null=True,
        blank=True
    )
    
    base = models.ForeignKey(
        Base,
        on_delete=models.CASCADE,
        verbose_name='在庫拠点',
    )
    
    registration_at = models.DateField(
        verbose_name='登録日',
        null=True,
        blank=True
    )
    
    remarks = models.TextField(
        verbose_name='備考',
        null=True,
        blank=True
    )
    
    def save(self, *args, **kwargs):
        if self.registration_at is None and not self.id:
            self.registration_at = timezone.now()
        self.total_price = self.price
        super(StorageItem, self).save(*args, **kwargs)
        if self.id is not None:
            for option in self.option.all():
                self.total_price += option.price
        super(StorageItem, self).save(*args, **kwargs)
    
    def __str__(self):
        return f'{self.item} ({self.base})'
    
    class Meta:
        verbose_name = '貯蔵品'
        verbose_name_plural = '貯蔵品'


class KittingPlan(models.Model):
    objects = BaseManager()
    
    kitting_choice = (
        ('標準', '標準'),
        ('お急ぎ便', 'お急ぎ便')
    )
    name = models.CharField(
        verbose_name='プラン名',
        max_length=10,
        choices=kitting_choice,
        default='標準'
    )
    
    price = models.PositiveSmallIntegerField(
        verbose_name='金額',
    )
    
    due = models.PositiveSmallIntegerField(
        verbose_name='納期',
        default=7
    )
    
    def __str__(self):
        return f'{self.name} {self.price}円'
    
    class Meta:
        verbose_name = 'キッティング価格'
        verbose_name_plural = 'キッティング価格'


class OrderItem(models.Model):
    objects = BaseManager()
    
    storage_item = models.ForeignKey(
        StorageItem,
        on_delete=models.CASCADE,
        verbose_name='貯蔵品'
    )
    
    quantity = models.PositiveSmallIntegerField(
        verbose_name='数量',
        default=1
    )
    
    ordered = models.BooleanField(
        verbose_name='確保済み',
        default=False
    )
    
    kitting_plan = models.ForeignKey(
        KittingPlan,
        on_delete=models.CASCADE,
        null=True,
        blank=True
    )
    
    price = models.PositiveIntegerField(
        verbose_name='合計金額',
        null=True,
        blank=True
    )
    
    due_at = models.DateField(
        verbose_name='納品予定日',
        null=True,
        blank=True
    )
    
    requester = models.ForeignKey(
        Requester,
        on_delete=models.CASCADE,
        verbose_name='依頼者',
    )
    
    def save(self, *args, **kwargs):
        item_price = self.storage_item.total_price
        price = item_price * self.quantity
        kitting_plan = self.kitting_plan
        if kitting_plan is not None:
            now = datetime.datetime.now()
            hour = now.hour
            day = kitting_plan.due
            over_day = day + 1
            if hour >= 17:
                date = datetime.date.today() + datetime.timedelta(days=over_day)
            else:
                date = datetime.date.today() + datetime.timedelta(days=day)
            self.due_at = date
            self.price = price + kitting_plan.price
        else:
            self.price = price
        super(OrderItem, self).save(*args, **kwargs)
    
    def __str__(self):
        return f'{self.storage_item} × {self.quantity}'
    
    class Meta:
        verbose_name = '確保アイテム'
        verbose_name_plural = '確保アイテム'


class StorageCart(models.Model):
    objects = BaseManager()
    
    requester = models.ForeignKey(
        Requester,
        on_delete=models.CASCADE,
        verbose_name='依頼者'
    )
    
    order_item = models.ManyToManyField(
        OrderItem,
        verbose_name='確保アイテム',
    )
    
    price = models.PositiveIntegerField(
        verbose_name='合計金額（税込み）',
        null=True,
        blank=True
    )
    
    tax_price = models.PositiveSmallIntegerField(
        verbose_name='消費税',
        null=True,
        blank=True
    )
    
    ordered = models.BooleanField(
        default=False
    )
    
    def save(self, *args, **kwargs):
        if self.pk is not None:
            self.price = 0
            subtotal = 0
            tax = 0.1
            self.tax_price = 0
            for item in self.order_item.all():
                subtotal += item.storage_item.total_price * item.quantity
                if item.kitting_plan is not None:
                    subtotal += item.kitting_plan.price
            self.tax_price += round(subtotal * tax)
            self.price += subtotal + self.tax_price
        super(StorageCart, self).save(*args, **kwargs)
    
    def __str__(self):
        return self.requester.user.screenname
    
    class Meta:
        verbose_name = '貯蔵品カート'
        verbose_name_plural = '貯蔵品カート'


class Approve(models.Model):
    last_name = models.CharField(
        verbose_name='姓',
        max_length=32
    )
    
    first_name = models.CharField(
        verbose_name='名',
        max_length=32,
    )
    
    dept_code = models.PositiveSmallIntegerField(
        verbose_name='部門コード'
    )
    
    dept_name = models.CharField(
        verbose_name='部門名',
        max_length=255
    )
    
    requester = models.ForeignKey(
        Requester,
        on_delete=models.CASCADE,
        verbose_name='依頼者',
        null=True,
        blank=True
    )
    
    def __str__(self):
        return f'{self.last_name} {self.first_name}'
    
    class Meta:
        verbose_name = '承認者情報'
        verbose_name_plural = '承認者情報'


class OrderInfo(models.Model):
    status_choices = (
        ('1', '準備中'),
        ('2', '確保済み'),
        ('3', 'キッティング中'),
        ('4', 'キッティング完了'),
        ('5', '納品済み')
    )
    
    objects = BaseManager()
    
    status = models.CharField(
        verbose_name='ステータス',
        max_length=2,
        choices=status_choices,
        default=1
    )
    
    number = models.CharField(
        verbose_name='受注番号',
        max_length=100
    )
    
    ticket = models.PositiveIntegerField(
        verbose_name='チケット番号',
        null=True,
        blank=True
    )
    
    storage_cart = models.ForeignKey(
        StorageCart,
        on_delete=models.CASCADE,
        verbose_name='カート'
    )
    
    approve = models.ForeignKey(
        Approve,
        on_delete=models.CASCADE,
        verbose_name='承認者情報'
    )
    
    requester = models.ForeignKey(
        Requester,
        on_delete=models.CASCADE,
        verbose_name='依頼者'
    )
    
    contact_user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='担当者',
        null=True,
        blank=True,
        related_name='contact_user'
    )
    
    ordered_at = models.DateTimeField(
        verbose_name='依頼日',
        null=True,
        blank=True
    )
    
    updated_at = models.DateTimeField(
        verbose_name='更新日',
        null=True,
        blank=True
    )
    
    completed_delivery = models.BooleanField(
        verbose_name='納品済み',
        default=False
    )
    
    delivery_at = models.DateTimeField(
        verbose_name='納品日',
        null=True,
        blank=True
    )
    
    due_at = models.DateField(
        verbose_name='納品予定日',
        null=True,
        blank=True
    )
    
    def save(self, *args, **kwargs):
        if not self.id:
            self.ordered_at = timezone.now()
        self.updated_at = timezone.now()
        if self.delivery_at is not None:
            self.completed_delivery = True
        due = []
        for item in self.storage_cart.order_item.all():
            due.append(item.due_at)
        due.sort()
        self.due_at = due[-1]
        super(OrderInfo, self).save(*args, **kwargs)
    
    def __str__(self):
        return f'{self.number}'
    
    class Meta:
        verbose_name = '依頼内容'
        verbose_name_plural = '依頼内容'

stock/forms.py
from django import forms
from bootstrap_modal_forms.forms import BSModalModelForm

from .models import Option, StorageItem, Approve, OrderInfo


class StorageItemBSModalForm(BSModalModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
    
    class Meta:
        model = StorageItem
        fields = ('order_number', 'item', 'price', 'quantity', 'option', 'base', 'registration_at', 'remarks')


class StorageItemUpdateBSModalForm(BSModalModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['item'].widget.attrs['readonly'] = 'readonly'
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
    
    class Meta:
        model = StorageItem
        fields = ('order_number', 'item', 'price', 'quantity', 'option', 'base', 'registration_at', 'remarks')


class OptionCreateBSModalForm(BSModalModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
    
    class Meta:
        model = Option
        fields = ('maker', 'name', 'price', 'quantity', 'remarks')


class ApproveBSModalForm(BSModalModelForm):
    def __init__(self, *args, **kwargs):
        super(ApproveBSModalForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
        self.fields['requester'].initial = kwargs['request'].user
    # self.fields['requester'].widget.attrs['disabled'] = True
    
    class Meta:
        model = Approve
        fields = ('last_name', 'first_name', 'dept_code', 'dept_name', 'requester')


class OrderInfoBSModalForm(BSModalModelForm):
    def __init__(self, *args, **kwargs):
        super(OrderInfoBSModalForm, self).__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
        self.fields['number'].widget.attrs['readonly'] = 'readonly'
    
    class Meta:
        model = OrderInfo
        fields = ('number', 'ticket', 'contact_user')

templates/stock/approve.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load humanize %}
{% load extras %}

{% block content %}

	<a href="{% url 'stock:cart' %}">
        <i class="fas fa-long-arrow-alt-left"></i>カートに戻る
    </a>
	<div class="container my-5">
		<div class="row page-title">
			<h2 class="title-text">依頼内容確認・変更画面</h2>
		</div>
		<div class="row mt-5">
			<div class="col-9">
				<div class="row approve-menu">
					<div class="col-3">
						<span class="menu-title">1 依頼者情報</span>
					</div>
					<div class="col-8">
						<p>{{ request.user.screenname }}</p>
						<p>{{ request.user.department }}</p>
					</div>
				</div>
				<div class="row approve-menu mt-2">
					<div class="col-3">
						<span class="menu-title">2 承認者情報</span>
					</div>
					{% if approve is not None%}
						<div class="col-8">
							<p>{{ approve }}</p>
							<p>部門コード：{{ approve.dept_code }}</p>
							<p>部門名：{{ approve.dept_name }}</p>
						</div>
						<div class="col-1">
							<a href="#" class="update-approve">変更</a>
						</div>
					{% else %}
						<div class="col-8">
							<a href="#" class="create-approve">登録</a>
						</div>
					{% endif %}
				</div>
				<div class="row mt-2">
					<div class="col-4">
						<span class="menu-title">3 商品とお届け情報の確認</span>
					</div>
				</div>
				<div class="row">
					{% for order_item in cart.order_item.all %}
						<div class="card mt-3 approve-item">
							<div class="card-body">
								<div class="row">
									<p class="schedule">お届け予定日：
										<span class="schedule-date{{ order_item.pk }}">
											{% if order_item.due_at is not None %}
												{{ order_item.due_at }}
											{% else %}
												お問い合わせください
											{% endif %}
										</span>
									</p>
									<div class="col-2">
										{% if order_item.storage_item.item.pc.img.name == '' %}
	                                        <img src="/media/images/no_image_logo.png" alt="noimage" class="item-img">
	                                    {% else %}
	                                        <img src="{{ order_item.storage_item.item.pc.img.url }}" alt="{{ storage_item.item.pc.name }}" class="item-img">
	                                    {% endif %}
									</div>
									<div class="col-4">
										<p class="item-name mb-1">{{ order_item.storage_item }}</p>
										<p class="item-price">￥
											<span id="itemPrice{{ order_item.pk }}">{{ order_item.pk | total_price | intcomma}}</span>
										</p>
										<p>
{#											<label for="quantity{{ order_item.pk }}">数量：</label>#}
{#											<select name="" id="quantity{{ order_item.pk }}"></select>#}
											数量：{{ order_item.quantity }}
	                                    </p>
									</div>
									<div class="col-3">
										<p class="item-name">付属品</p>
										{% for option in order_item.storage_item.option.all %}
											<p class="mb-1">{{ option }}</p>
											<p class="item-price"> ￥{{ option.price | intcomma}}</p>
										{% empty %}
											なし
										{% endfor %}
									</div>
									<div class="col-3">
										<p class="item-name">キッティングオプション</p>
										<form action="#" method="post">
											{% csrf_token %}
											{% for plan in kitting_plan %}
												<div class="form-check">
													<label for="kittingPlan{{ plan.pk }}_{{ order_item.pk }}">
														{{ plan.name }}￥{{ plan.price | intcomma }}
													</label>
													<input type="radio" class="form-check-input select-plan" id="kittingPlan{{ plan.pk }}_{{ order_item.pk }}"
													       name="kittingSelect{{ order_item.pk }}" value="{{ plan.price }}"
															{% if plan.pk == order_item.kitting_plan.pk %}
																checked
															{% endif %}>
												</div>
											{% endfor %}
										</form>
									</div>
								</div>
							</div>
						</div>
					{% endfor %}
				</div>
			</div>
			<div class="col-3">
				<div class="card approve-card">
					<div class="card-body">
						<div class="row bottom-border">
							<button type="button" class="btn btn-warning my-3" id="confirm"
							        {% if approve is None %}disabled{% endif %}>
								注文を確定
							</button>
						</div>
						<div class="row bottom-border mb-3">
							<p><span class="confirm-text">注文内容</span>(税込み)</p>
							<p class="mb-1">
								商品の小計：
								<span class="confirm-price float-end">￥
									<span class="subtotal-price">
										{{ cart.pk | subtotal_price | intcomma }}
									</span>
								</span>
							</p>
							<p class="mb-1">
								キッティング費用：
								<span class="confirm-price float-end">￥
									<span class="total-kitting-price">{{ cart.pk | kitting_price | intcomma }}</span>
								</span>
							</p>
						</div>
						<div class="row bottom-border mb-3">
							<p class="confirm-text">
								ご請求額：
								<span class="float-end">￥
									<span class="total-price">
										{{ cart.price | intcomma }}
									</span>
								</span>
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock content %}

{% block javascript %}

	<script type="text/javascript">
		const confirm = document.querySelector('#confirm');
		const next_url = "{% url 'stock:add_order_info' %}"
		linkClick(confirm, next_url);

		$(".create-approve").each(function () {
			$(this).modalForm({formURL: "{% url 'stock:approve_create' %}"});
		});


		{% if approve is not None %}
			$(".update-approve").each(function() {
				$(this).modalForm({formURL: "{% url 'stock:approve_update' approve.pk %}"});
			});
		{% endif %}

		const modal = document.querySelector('#modal');

		$('#modal').on('show.bs.modal', function() {
			formSubmit();
		});

        //ajax

		{% for order_item in cart.order_item.all %}
			{#let quantity_el{{ order_item.pk }} = document.querySelector('#quantity{{ order_item.pk }}');#}
            {#value = {#}
            {#    storage_item: {{ order_item.storage_item.pk }},#}
	        {#    requester: {{ order_item.requester.pk }}#}

            {#quantity(quantity_el{{ order_item.pk }}, {{ order_item.storage_item.quantity }}, {{ order_item.quantity }});#}
            {#quantityChange(quantity_el{{ order_item.pk }}, value, {{ order_item.pk }});#}

			const scheduleDate{{ order_item.pk }} = document.querySelector('.schedule-date{{ order_item.pk }}');

			{% for plan in kitting_plan %}
				let checkId{{ plan.pk }}_{{ order_item.pk }} = '#kittingPlan{{ plan.pk }}_{{ order_item.pk }}';
				let data{{ plan.pk }}_{{ order_item.pk }} = {
					storage_item: {{ order_item.storage_item.pk }},
					quantity: {{ order_item.quantity }},
					requester: {{ request.user.pk }},
					kitting_plan: {{ plan.pk }}
				}
				const radioEl{{ plan.pk }}_{{ order_item.pk }} = document.querySelector(
					checkId{{ plan.pk }}_{{ order_item.pk }}
				);
				changeRadio(
					radioEl{{ plan.pk }}_{{ order_item.pk }},
					data{{ plan.pk }}_{{ order_item.pk }},
					{{ order_item.pk }},
					scheduleDate{{ order_item.pk }},
					{{ order_item.quantity }}
				);

			{% endfor %}
		{% endfor %}

	</script>

{% endblock javascript %}

templates/stock/cart.html
{% extends 'base.html' %}
{% load static %}
{% load django_bootstrap5 %}
{% load humanize %}
{% load extras %}

{% block content %}

	<div class="container my-5">
		<div class="row page-title">
			<h2 class="title-text">依頼予定のPC</h2>
		</div>
		<div class="row mt-5">
			<a href="{% url 'stock:storage_list' %}">
				<i class="fas fa-long-arrow-alt-left"></i>リストに戻る
			</a>
			<div class="col-9">
				{% if storagecart is not None %}
					<div class="card">
						<div class="card-body">
							追加されました
						</div>
					</div>
				{% endif %}
				<div class="card">
					<div class="card-body cart">
						<div class="row bottom-border cart__header">
							<div class="col-11">
								<p class="cart__title">ショッピングカート</p>
							</div>
							<div class="col-1">
								<p class="header-price">価格</p>
							</div>
						</div>
						{% for order_item in storagecart.order_item.all %}
							<div class="row bottom-border mt-3 cart__item">
								<div class="col-4 text-center">
									{% if order_item.storage_item.item.pc.img.name == '' %}
										<img src="/media/images/no_image_logo.png" alt="noimage" class="cart__image">
									{% else %}
										<img src="{{ order_item.storage_item.item.pc.img.url }}"
										     alt="{{ storage_item.item.pc.name }}" class="cart__image">
									{% endif %}
								</div>
								<div class="col-6">
									<p class="cart__item__name">
										{{ order_item.storage_item.item.pc.maker }} {{ order_item.storage_item.item.pc.name }}
									</p>
									<p class="cart__item__location">
										拠点 {{ order_item.storage_item.base }} {{ order_item.storage_item.order_number }}
									</p>
									<div class="row">
										<div class="col-7 cart__item__menu">
											本体価格：￥{{ order_item.storage_item.price | intcomma }}</div>
									</div>
									<div class="row">
										<div class="col-2 cart__item__menu">付属品</div>
										<div class="col-7">
											{% for option in order_item.storage_item.option.all %}
												<p>{{ option.name }}：￥{{ option.price | intcomma }}</p>
											{% empty %}
												<p>なし</p>
											{% endfor %}
										</div>
									</div>
									<div class="row">
										<div class="col-7 cart__item__menu">
											キッティング費用：
											￥{{ order_item.kitting_plan.price | intcomma }}（{{ order_item.kitting_plan.name }}）
										</div>

									</div>
									<div class="row">
										<div class="col-5 cart__item__menu">
											<label for="quantity{{ order_item.pk }}">数量：</label>
											<select name="" id="quantity{{ order_item.pk }}"></select>
										</div>
										<div class="col-3">
											<a href="{% url 'stock:remove_cart' order_item.pk %}">
												削除
											</a>
										</div>
									</div>


								</div>
								<div class="col-2">
									<p class="cart__item__price float-end">
										￥<span class="item-price"
										       id="itemPrice{{ order_item.pk }}">{{ order_item.price | add_tax | intcomma }}</span>
									</p>
								</div>
							</div>
						{% empty %}
							<p class="mb-3">アイテムが選択されていません</p>
						{% endfor %}
						<div class="row cart__footer">
							<span class="cart__total__title">小計({{ count }}個のアイテム) (税込み):</span>
							<span class="cart__total__price">
								￥<span class="total-price">{{ storagecart.price | intcomma }}</span>
							</span>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-3">
				<div class="card cart__total">
					<div class="card-body">
						<div class="row">
	                        <span class="cart__total__title">
	                            小計({{ count }}個のアイテム) (税込み)
	                        </span>
							<p>:
								<span class="cart__total__price">￥
									<span class="total-price">{{ storagecart.price | intcomma }}</span>
								</span>
							</p>
						</div>
						<div class="row">
							<button type="button" class="btn btn-sm btn-warning my-3"
							        onclick="location.href='{% url "stock:approve" %}';">
								次に進む
							</button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock content %}

{% block javascript %}
	<script type="text/javascript">

        {% for order_item in storagecart.order_item.all %}
            let quantity_el{{ order_item.pk }} = document.querySelector('#quantity{{ order_item.pk }}');

            data = {
                storage_item: {{ order_item.storage_item.pk }},
                price: {{ order_item.price }},
                requester: {{ order_item.requester.pk }},
            }
            quantity(quantity_el{{ order_item.pk }}, {{ order_item.storage_item.quantity }}, {{ order_item.quantity }});
            quantityChange(quantity_el{{ order_item.pk }}, data, {{ order_item.pk }});
        {% endfor %}

	</script>

{% endblock javascript %}

templates/stock/orderinfo_delete.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% load humanize %}

{% block content %}

	<div class="container delete-confirm my-5">
		<div class="row">
			<div class="col-9 offset-2">
				<a href="{% url 'stock:my_order_info' %}">
			        <i class="fas fa-long-arrow-alt-left"></i>依頼履歴に戻る
		        </a>
				<div class="card mt-3">
					<div class="card-body">
						<h3>
							<span class="delete-confirm__icon">
								<i class="fa-solid fa-circle-info"></i>
							</span>
							以下の依頼をキャンセルしました。
						</h3>
						{% for order_item in order_item_list %}
							<div class="row mt-3">
								<div class="col-4 text-center">
									{% if order_item.storage_item.item.pc.img.name == '' %}
                                        <img src="/media/images/no_image_logo.png" alt="noimage">
                                    {% else %}
                                        <img src="{{ order_item.storage_item.item.pc.img.url }}" alt="{{ storage_item.item.pc.name }}">
                                    {% endif %}
								</div>
								<div class="col-8">
									<div class="row">
										<span>{{ order_item.storage_item.item }}</span>
										<span>CPU：{{ order_item.storage_item.item.cpu }}</span>
										<span>メモリ：{{ order_item.storage_item.item.memory }}GB</span>
										<span>ストレージ：{{ order_item.storage_item.item.storage }}</span>
										<span>本体価格：￥{{ order_item.storage_item.total_price | intcomma }}</span>
									</div>
									<div class="row">
										<span>数量：{{ order_item.quantity }}</span>
									</div>
								</div>
							</div>
						{% endfor %}
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock content %}

templates/stock/storate_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>